#!/bin/sh
ls -da -1 app/code/community/Phoenix/* | sed 's/\(.*\)/\1 \1/' > modman
ls -da -1 app/code/core/*/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/adminhtml/default/default/layout/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/adminhtml/default/default/template/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/adminhtml/default/default/locale/en_US/translate.csv | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/base/default/etc/widget.xml | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/base/default/layout/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/base/default/template/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/default/etc/widget.xml | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/default/layout/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/default/locale/en_US/translate.csv | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/default/template/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/iphone/etc/widget.xml | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/iphone/layout/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/iphone/locale/en_US/translate.csv | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/frontend/enterprise/iphone/template/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/design/install | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/etc/config.xml | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/etc/enterprise.xml | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/etc/local.xml.* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/etc/modules/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/locale/*/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 app/Mage.php | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 api.php | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 cr* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 downloader | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 errors | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 favicon.ico | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 get.php | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 includes/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 index.ph* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 install.php | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/blank.html | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/calendar/ | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/enterprise/adminhtml/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/extjs/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/firebug/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/flash/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/index.php | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/jscolor/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/lib/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/mage/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/prototype | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/scriptaculous | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/spacer.gif | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/tiny_mce | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 js/varien | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 lib/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 LIC* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 mage | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 media/dhl/logo.jpg | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 media/xmlconnect | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 php.ini.sample | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 pkginfo/Mage_All* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 RELEASE_NOTES.txt | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 shell/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/adminhtml/default/default/*.css | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/adminhtml/default/default/images/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/adminhtml/default/default/lib/prototype | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/adminhtml/default/default/media/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/adminhtml/default/default/xmlconnect/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/adminhtml/default/enterprise/boxes.css | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/adminhtml/default/enterprise/images/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/base/default/favicon.ico | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/base/default/css/widgets.css | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/base/default/images/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/base/default/js/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/base/default/lib/prototype | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/default/css/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/default/favicon.ico | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/default/images/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/default/js/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/iphone/favicon.ico | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/iphone/css/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/iphone/images/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/frontend/enterprise/iphone/js/* | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 skin/install | sed 's/\(.*\)/\1 \1/' >> modman
ls -da -1 var/package/* | sed 's/\(.*\)/\1 \1/' >> modman
